name: IPLFantasyPro
options:
  bundleIdPrefix: com.iplfantasy
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

packages:
  FirebaseAuth:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 10.20.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    version: 7.10.0
  Starscream:
    url: https://github.com/daltoniam/Starscream
    version: 4.0.6

targets:
  IPLFantasyPro:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.iplfantasy.pro
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: FirebaseAuth
      - package: Kingfisher
      - package: Starscream
    info:
      path: Sources/App/Info.plist
      properties:
        CFBundleDisplayName: IPL Fantasy Pro
        CFBundleName: IPLFantasyPro
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: AccentColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
